### PR TITLE
Allow to retrieve only translations or source for git flow

### PR DESCRIPTION
**Pull request by rGaillard**

### CODE REVIEW

**Comment by sergioisidoro** [comment]
Looks good :) Don't mind the CI, because I was not yet able to get the Open Source pricing plan for the organization used for the integration tests. 

Could you add mention to these inputs in the readme? 

**edit** also would be great to add a default behaviour. Right now this PR will not provide a default behaviour if those inputs are not provided. `action.yml` should be updated if we would like to make these parameters mandatory: 

https://github.com/sergioisidoro/github-transifex-action/blob/master/action.yml#L17

**Comment by rGaillard** [comment]
I have updated the README, however, i reuse variables already defined with default values but it break the BC.. Maybe we need to use separate variables for this specific flow to not break the BC?

And, thank you for this Github Action which is more flexible than the Transifex standard integration :)

**Comment by sergioisidoro** [comment]
Ah! True! Ok this may be a bit more complicated than I initially thought :)

Maybe the issue here is bad naming of these inputs from my part: in the git flow `INPUT_PULL_SOURCES` and `INPUT_PULL_TRANSLATIONS` are actually about pulling the strings into the PR (ie creating a commit in the PR with the up to date strings). In this PR we're talking about pulling the strings from transifex to first handle the merging before doing anything else (pushing to transifex or pulling the strings into the PR)
 
I assumed you are proposing this change because you want to speed up the process, and not have to pull all the files, right? Or is there other reason?

**Comment by sergioisidoro** [comment]
I took a bit of time to look a the problem. Would something like this fix this issue? There's a new input `commit_to_pr` to differentiate the pulling from the committing. Also updated the readme with a couple of examples. Feedback is appreciated!

https://github.com/sergioisidoro/github-transifex-action/compare/sellective-pulling

(Added you to the contributors on that Readme update)

**Comment by rGaillard** [comment]
Yes, i think that adding this new option is a good idea. And thank you for adding new examples, they can be useful for new users of this github action.
In my case, i want to rely on Transifex for translated strings only (and not for sources), the goal of this initial PR.

Thank you for adding me on the contributors.
I close this PR, let's continue the discussion on the new one when you will create it if needed.

**Pull request closed without merging**
